import fs from "node:fs";
import path from "node:path";
import type { ToolSchema } from "./types";

/**
 * Loads data/wall.json. The paired "your code / what the model sees" view.
 * Generated by agent/export_wall.py directly from the function objects, so
 * the source shown on the site cannot drift from the source that ran.
 */

export interface WallTool {
  name: string;
  opaque_name: string;
  python_source: string;
  python_lines: number;
  docstring: string;
  complete: ToolSchema;
  lazy: ToolSchema;
}

export interface Wall {
  note: string;
  tools: WallTool[];
}

export function loadWall(): Wall {
  const raw = fs.readFileSync(
    path.join(process.cwd(), "data", "wall.json"),
    "utf-8",
  );
  return JSON.parse(raw) as Wall;
}

/** Totals for the headline stat: how much code exists vs how much is visible. */
export function wallTotals(wall: Wall) {
  const pythonLines = wall.tools.reduce((n, t) => n + t.python_lines, 0);
  const completeChars = wall.tools.reduce(
    (n, t) => n + t.complete.description.length,
    0,
  );
  const lazyChars = wall.tools.reduce((n, t) => n + t.lazy.description.length, 0);
  return { pythonLines, completeChars, lazyChars, toolCount: wall.tools.length };
}
