"""
Exports data/wall.json - the paired view behind "The Wall" on the site.

For every tool, this captures three things side by side:

  - the real Python source of the function, read straight off the function
    object with inspect.getsource
  - the COMPLETE declaration the model would see
  - the LAZY declaration the model would see instead

The source is extracted rather than copied so the website can never drift
from the code it claims to be showing. If someone edits tools.py and forgets
to re-run this, the diff shows up in git rather than silently misleading a
reader.

Run:
    python export_wall.py
"""

import inspect
import json
from pathlib import Path

import tools
from schemas import TOOL_SCHEMAS
from schemas_lazy import LAZY_TOOL_SCHEMAS
from variants import OPAQUE_NAMES

OUT = Path(__file__).resolve().parent.parent / "data" / "wall.json"

TOOL_ORDER = [
    "get_flight_status",
    "search_passenger",
    "maintenance_history",
    "find_available_gate",
    "lookup_aircraft",
    "get_weather",
]


def _by_name(schemas):
    return {s["name"]: s for s in schemas}


def main() -> None:
    complete = _by_name(TOOL_SCHEMAS)
    lazy = _by_name(LAZY_TOOL_SCHEMAS)

    payload = {
        "note": (
            "Generated by agent/export_wall.py. The python_source field is read "
            "from the live function objects with inspect.getsource, so it cannot "
            "drift from tools.py."
        ),
        "tools": [],
    }

    for name in TOOL_ORDER:
        fn = getattr(tools, name)
        source = inspect.getsource(fn)
        payload["tools"].append({
            "name": name,
            "opaque_name": OPAQUE_NAMES[name],
            "python_source": source.rstrip() + "\n",
            "python_lines": len(source.rstrip().splitlines()),
            "docstring": inspect.getdoc(fn) or "",
            "complete": complete[name],
            "lazy": lazy[name],
        })

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"wrote {OUT} ({len(payload['tools'])} tools)")


if __name__ == "__main__":
    main()
